fix(vue2): Use the super constructor when the instance is a VueComponent
vuejs/devtools pull request #1690
Opened 2022-02-09 10:46 UTC by 0Rick0

Fixes #1687

2022-02-09 10:55 UTC, Akryum requested changes

2022-02-09 10:55 UTC, Akryum commented on packages/app-backend-core/src/app.ts
> +function _legacy_getVueFromApp (app) {
Could you add a comment explaining why we need to do this? Thanks!

2022-02-09 11:23 UTC, Akryum approved these changes

2022-02-09 11:24 UTC, merged

2022-03-09 02:14 UTC, masstez approved these changes